import {useState} from 'react';
import Link from 'next/link';
import Head from 'next/head';
import type {GetStaticPaths,GetStaticProps} from 'next';
import {products,money,productColors,coloredProduct,type Product} from '../../lib/catalog';
import {useCart} from '../../lib/cart';
import ProductGallery from '../../components/ProductGallery';
function Details({product}:{product:Product}){const [color,setColor]=useState('original');const colors=productColors(product);const selected=colors.find(c=>c.id===color)!;const [size,setSize]=useState(''),[message,setMessage]=useState('');const {add,ready}=useCart();return <main id="main" className="section"><Head><title>{product.title} — HOOD REVENGE</title></Head><Link className="text-link" href="/products">← Back to collection</Link><div className="product-detail"><ProductGallery product={coloredProduct(product,color)}/><div className="detail-copy"><p className="eyebrow">COLLECTION 001 / {product.category}</p><h1>{product.title}</h1><p className="detail-price">{money(product.price)}</p><p>{product.description}</p><fieldset><legend>Colour: {selected.name}</legend><div className="color-swatches">{colors.map(c=><button type="button" key={c.id} aria-label={`Choose ${c.name}`} aria-pressed={color===c.id} title={c.name} style={{backgroundColor:c.color}} onClick={()=>{setColor(c.id);setMessage('')}}/>)}</div></fieldset><fieldset><legend>Select size</legend><div className="sizes">{product.sizes.map(s=><button key={s} aria-pressed={s===size} className={s===size?'active':''} onClick={()=>{setSize(s);setMessage('')}}>{s}</button>)}</div></fieldset><button disabled={!ready} className="button button-outline w-full" style={{backgroundColor:selected.color,color:selected.ink}} onClick={()=>{if(!size){setMessage('Choose a size first.');return}add(product.id,size,color);setMessage(`${selected.name} / ${size} added to your bag. Maximum 10 per size.`)}}>Add to bag <span>+</span></button><p className="status" role="status">{message}</p>{message.includes('added')&&<Link className="text-link" href="/cart">View your bag →</Link>}<div className="sample-note">Preview item · Sample price · Not available for purchase</div><details><summary>Size & fit</summary><p>Available size options are for demonstration. Final garment measurements will be added before orders open.</p></details><details><summary>Delivery & returns</summary><p>Shipping regions, delivery charges and return terms have not been configured. No orders or payments are accepted in this preview.</p></details></div></div></main>}
export default function ProductPage({product}:{product:Product}){return <Details key={product.id} product={product}/>}
export const getStaticPaths:GetStaticPaths=async()=>({paths:products.map(p=>({params:{id:p.id}})),fallback:false});
export const getStaticProps:GetStaticProps=async({params})=>{const product=products.find(p=>p.id===params?.id);if(!product) return {notFound:true};
const {readdir} = await import('node:fs/promises');
const {join} = await import('node:path');
let files:string[] = [];
try {files = await readdir(join(process.cwd(),'public','images','products',product.id));} catch(error) {if((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;}
const photos = files.filter(name=>/\.(png|jpe?g|webp|avif)$/i.test(name)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map((name,index)=>({src:`/images/products/${product.id}/${encodeURIComponent(name)}`,alt:`${product.title} — ${name.replace(/\.[^.]+$/, '').replace(/^\d+[-_ ]*/, '').replace(/[-_]/g,' ') || `model view ${index+1}`}`}));
return {props:{product:{...product,photos}}}};
